// SPDX-License-Identifier: AGPL-3.0-or-later
package org.inkweft.core

import org.junit.Assert.*
import org.junit.Test
import java.util.UUID

class SelectionLearningTest {
    private fun id()=UUID.randomUUID().toString()
    private fun stroke(points:List<InkSample> = listOf(InkSample(10f,20f,0),InkSample(30f,20f,100)))=InkStroke(id(),InkPen.PEN,0xff000000.toInt(),2f,InkTool.STYLUS,points)
    private fun reject(f:()->Unit){try{f();fail("invalid state accepted")}catch(_:IllegalArgumentException){}}
    private fun complete(s:InkSession){val c=checkNotNull(s.nextCommand());s.complete(c,InkCommitResult.Committed(c.expectedRevision+1))}
    @Test fun rectangleSelectsOnlyEntireStroke(){val region=InkRegion(listOf(EraserPoint(5f,10f),EraserPoint(35f,30f)));assertTrue(region.selects(stroke()));assertFalse(region.selects(stroke(listOf(InkSample(10f,20f,0),InkSample(50f,20f,1)))))}
    @Test fun reversedRectangleIsNormalizedAndPolygonSelects(){val r=InkRegion(listOf(EraserPoint(50f,50f),EraserPoint(0f,0f)));assertTrue(r.selects(stroke()));val p=InkRegion(listOf(EraserPoint(0f,0f),EraserPoint(60f,0f),EraserPoint(60f,60f),EraserPoint(0f,60f)),false);assertTrue(p.selects(stroke()));assertFalse(p.contains(80.0,10.0))}
    @Test fun masksEncodeTheirExactShape(){for(r in listOf(InkRegion(listOf(EraserPoint(5f,5f),EraserPoint(25f,35f))),InkRegion(listOf(EraserPoint(0f,0f),EraserPoint(40f,0f),EraserPoint(20f,50f)),false))){val m=r.mask();val out=InkCutCodec.decode(InkCutCodec.encode(m));assertEquals(m.shape,out.shape);assertEquals(m.points,out.points);assertEquals(m.id,out.id)}}
    @Test fun newMaskSurvivesStrokeAndPageCodecs(){val cut=InkRegion(listOf(EraserPoint(15f,10f),EraserPoint(25f,30f))).mask();val s=stroke().withCuts(listOf(cut));val decoded=InkStrokeCodec.decode(InkStrokeCodec.encode(s));assertEquals(InkCutShape.RECTANGLE,decoded.cuts.single().shape);val page=InkPageFile("新擦除","",listOf(s));val parsed=ContentTransfer.decode(page.encode()).content as ContentTransfer.Content.Page;assertEquals(cut.points,parsed.value.strokes.single().cuts.single().points)}
    @Test fun roundMaskLegacyEncodingUnchanged(){val c=InkCut(id(),5f,listOf(EraserPoint(10f,10f)));val bytes=InkCutCodec.encode(c);assertEquals(InkCutShape.ROUND,InkCutCodec.decode(bytes).shape);assertTrue(bytes.size<200)}
    @Test fun copyMovesMasksAndSamplesWithIndependentIds(){val s=stroke().withCuts(listOf(InkRegion(listOf(EraserPoint(14f,5f),EraserPoint(20f,30f))).mask()));val c=InkSelectionEdit.copy(listOf(s),20f,25f).single();assertNotEquals(s.id,c.id);assertEquals(s.samples[0].x+20,c.samples[0].x,0f);assertEquals(s.samples[0].elapsedMs,c.samples[0].elapsedMs);assertNotEquals(s.cuts[0].id,c.cuts[0].id);assertEquals(InkCutShape.RECTANGLE,c.cuts[0].shape);assertEquals(s.cuts[0].points[0].y+25,c.cuts[0].points[0].y,0f)}
    @Test fun replaceUndoRedoRestoresOriginalSamplingAndVisibility(){val original=stroke();val session=InkSession(InkPage(id(),0,emptyList()));session.enqueue(InkMutation.Add(original));complete(session);val moved=InkSelectionEdit.copy(listOf(original),10f,10f);session.enqueue(InkMutation.Replace(listOf(original.id),moved));complete(session);assertEquals(moved.single().id,session.visibleDraft().single().id);assertEquals(original.samples,session.page.strokes.first().stroke.samples);assertFalse(session.page.strokes.first().visible);session.requestUndo();complete(session);assertEquals(original.id,session.visibleDraft().single().id);assertEquals(original.samples,session.visibleDraft().single().samples);session.requestRedo();complete(session);assertEquals(moved.single().id,session.visibleDraft().single().id)}
    @Test fun unknownReplaceKeepsSameOperation(){val s=InkSession(InkPage(id(),0,emptyList()));s.enqueue(InkMutation.Replace(emptyList(),listOf(stroke())));val c=s.nextCommand()!!;s.complete(c,InkCommitResult.Unknown);assertSame(c,s.retry());complete(s);assertEquals(1,s.page.strokes.size)}
    @Test fun pendingReplaceReservesFullDrawingBudget(){val original=List(13){stroke(List(7500){i->InkSample((10+i%800).toFloat(),40f,i.toLong())})};val s=InkSession(InkPage(id(),0,emptyList()));s.enqueue(InkMutation.Replace(emptyList(),original));assertFalse(s.canStart)}
    @Test fun smoothingKeepsAxesTimeEndpointsAndSharpCorners(){val points=listOf(InkSample(0f,10f,0,.4f),InkSample(10f,10.5f,10,.4f),InkSample(20f,10f,20,.8f),InkSample(20f,30f,30,.6f));val original=stroke(points);val smoothed=InkSelectionEdit.beautify(listOf(original),1f).single();assertEquals(points.first(),smoothed.samples.first());assertEquals(points.last(),smoothed.samples.last());assertEquals(points[2],smoothed.samples[2]);assertEquals(points.map{it.elapsedMs},smoothed.samples.map{it.elapsedMs});assertEquals(points.map{it.pressure},smoothed.samples.map{it.pressure});assertTrue(smoothed.samples[1].y<points[1].y)}
    @Test fun smoothingRejectsErasedInkAndZeroStrengthLeavesSamples(){val s=stroke();assertEquals(s.samples,InkSelectionEdit.beautify(listOf(s),0f).single().samples);reject{InkSelectionEdit.beautify(listOf(s.withCuts(listOf(InkCut(id(),3f,listOf(EraserPoint(10f,20f)))))),.5f)}}
    @Test fun recolorPreservesMasksAndHighlighterAlpha(){val s=InkStroke(id(),InkPen.HIGHLIGHTER,0x55ffff00,15f,InkTool.TOUCH,stroke().samples);val recolored=InkSelectionEdit.recolor(listOf(s),0xff334499.toInt()).single();assertEquals(0x55334499,recolored.color);assertEquals(s.samples,recolored.samples)}
    @Test fun sourceIdentityDefensivelyCopiesLists(){val ids=mutableListOf(id());val source=StudySourceDraft(id(),2,CanvasBounds(0.0,0.0,10.0,10.0),ids);ids.clear();assertEquals(1,source.strokeIds.size)}
    @Test fun graphRejectsCyclesMissingParentAndInvalidNumbers(){val a=StudyNode(id(),id(),null,0.0,0.0);val b=StudyNode(id(),id(),a.id,100.0,0.0);reject{StudyGraph.validate(listOf(a.copy(parentId=b.id),b))};reject{StudyGraph.validate(listOf(a.copy(parentId=id())))};reject{StudyGraph.validate(listOf(a.copy(x=Double.NaN)))}}
    @Test fun multipleOccurrencesShareOneCardAndLayoutDoesNotChangeIdentity(){val card=id();val a=StudyNode(id(),card,null,0.0,0.0);val b=StudyNode(id(),card,a.id,0.0,0.0);StudyGraph.validate(listOf(a,b));val layout=StudyGraph.arrange(listOf(a,b));assertEquals(setOf(a.id,b.id),layout.keys);assertTrue(layout.getValue(b.id).x>layout.getValue(a.id).x);assertEquals(card,b.cardId)}
    @Test fun removedParentCannotOwnVisibleChild(){val a=StudyNode(id(),id(),null,0.0,0.0,removed=true);val b=StudyNode(id(),id(),a.id,10.0,10.0);reject{StudyGraph.validate(listOf(a,b))}}
    @Test fun studyDigestBindsPayloadAndGraphRevision(){val book=id();val c=id();val node=id();val command=id();val a=StudyCommand(command,book,StudyAction.CREATE,c,node,title="摘要",body="A");val b=StudyCommand(command,book,StudyAction.CREATE,c,node,title="摘要",body="B");assertNotEquals(a.digest(),b.digest());val n=StudyNode(node,c,null,0.0,0.0);assertNotEquals(StudyGraph.orderHash(listOf(n)),StudyGraph.orderHash(listOf(n.copy(revision=2))))}
    @Test fun exactRegionDoesNotContainBlankOrDegenerateSelection(){reject{InkRegion(listOf(EraserPoint(1f,1f),EraserPoint(1f,5f)))};reject{StudyCommand(id(),id(),StudyAction.CREATE,id(),id(),title=" ")}}
}
