#!/usr/bin/env node
/* Build a single, self-contained index.html from src/.

   Why one file: the sample must open by double-click with no server, no network
   and no build toolchain. The sources stay modular and the concatenation order is
   explicit, so nothing is hidden inside a bundler.

   Run:  node tools/build.js
*/
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');

/* Order matters: every module only depends on the ones above it. */
const MODULES = [
  '00-core.js',
  '10-vault.js',
  '20-document.js',
  '30-commands.js',
  '40-store.js',
  '50-export.js',
  '60-seed.js',
  '70-ui.js'
];

function main() {
  const template = fs.readFileSync(path.join(SRC, 'index.template.html'), 'utf8');
  const css = fs.readFileSync(path.join(SRC, 'style.css'), 'utf8');

  const parts = MODULES.map((name) => {
    const body = fs.readFileSync(path.join(SRC, name), 'utf8');
    /* Only real module statements count: `exportPresentation:` is a method name,
       not an ESM export. */
    const esm = /^\s*import\s+[\w{*'"]|^\s*import\s*\(|^\s*export\s+(?:default|const|let|var|function|class|\{|\*)/m;
    if (esm.test(body)) {
      throw new Error(`${name} uses ESM syntax; modules must be plain scripts for the inline build`);
    }
    return `/* ===== ${name} ${'='.repeat(Math.max(0, 66 - name.length))} */\n${body.trim()}\n`;
  });

  const scripts = parts.join('\n');
  const out = template
    .replace('/*__STYLES__*/', () => css.trim())
    .replace('/*__SCRIPTS__*/', () => scripts);

  const banner = `<!--
  InkWeft S1 sample — generated by tools/build.js. Do not edit this file.
  Sources: src/00-core.js .. src/70-ui.js. Rebuild: node tools/build.js
  Runtime: zero dependencies, no network, works from file:// or any static server.
-->
`;
  const target = path.join(ROOT, 'index.html');
  fs.writeFileSync(target, banner + out, 'utf8');

  const bytes = fs.statSync(target).size;
  const assets = fs.readdirSync(path.join(ROOT, 'assets'))
    .map((f) => `  assets/${f} (${fs.statSync(path.join(ROOT, 'assets', f)).size} B)`);

  console.log(`built ${path.relative(ROOT, target)} from ${MODULES.length} modules`);
  console.log(`  html   ${bytes} bytes`);
  console.log(`  assets:\n${assets.join('\n')}`);
}

main();
